// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-InA3FMJpCrTt3lNhAdJswUv_HlBP3Q',
    appId: '1:964421032428:web:bb214bf8d40dee912208c9',
    messagingSenderId: '964421032428',
    projectId: 'mind-space-6b8f0',
    authDomain: 'mind-space-6b8f0.firebaseapp.com',
    storageBucket: 'mind-space-6b8f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8nTCjrx5vPBBZj2QbWH0tLEtdbXM9Z1U',
    appId: '1:964421032428:android:ccb3f8d760ab0b5f2208c9',
    messagingSenderId: '964421032428',
    projectId: 'mind-space-6b8f0',
    storageBucket: 'mind-space-6b8f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx4cBiyc2jiwtLQSH44w7OKkm0EK-MQM0',
    appId: '1:964421032428:ios:195c6ba0fc40b5722208c9',
    messagingSenderId: '964421032428',
    projectId: 'mind-space-6b8f0',
    storageBucket: 'mind-space-6b8f0.firebasestorage.app',
    iosBundleId: 'com.example.mindSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx4cBiyc2jiwtLQSH44w7OKkm0EK-MQM0',
    appId: '1:964421032428:ios:195c6ba0fc40b5722208c9',
    messagingSenderId: '964421032428',
    projectId: 'mind-space-6b8f0',
    storageBucket: 'mind-space-6b8f0.firebasestorage.app',
    iosBundleId: 'com.example.mindSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-InA3FMJpCrTt3lNhAdJswUv_HlBP3Q',
    appId: '1:964421032428:web:bd06ab6c676eccf52208c9',
    messagingSenderId: '964421032428',
    projectId: 'mind-space-6b8f0',
    authDomain: 'mind-space-6b8f0.firebaseapp.com',
    storageBucket: 'mind-space-6b8f0.firebasestorage.app',
  );
}
